apiVersion: v1
kind: Namespace
metadata:
  name: ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ns
  name: roboshop-pod
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"] # actions on resources, create, read, update, delete